### ISSUE TITLE
Phalcon and Devilbox

### ISSUE THREAD

**Issue by torsoe** [phalcon/documentation#11]
maybe it would be nice to tell on the Devilbox Environment Page that Phalcon and PSR are not enabled by default and has to be enabled in .env file at PHP_MODULES_ENABLE=psr, phalcon

**Comment by niden** [comment]
From reading their documentation, the modules are enabled by default. 

Since it has been a very long time until I managed to respond to this ticket, I presume that this was old behavior by Devilbox. I will close this and if it persists we can open a new issue.

Thank you for reporting this @torsoe
