### ISSUE TITLE
The variable name in the example of renderDecorated() in Forms is confusing

### ISSUE THREAD

**Issue by s-ohnishi** [phalcon/documentation#118]
The explanation of renderDecorated() given as an [example](https://docs.phalcon.io/5.6/forms/#__code_104) of how to use Forms is shown below.
```PHP
echo $element->renderDecorated('nameLast');
echo $element->renderDecorated('nameFirst');
```
but this gives the impression that renderDecorated() is a method of an element.
In fact, it is a method of the `ContactForm` class that extends `Forms`, so a variable name like `$form` instead of `$element` would be less confusing.

**Comment by niden** [comment]
Thank you @s-ohnishi 

Resolved in 8b554d5965d225aa00aed920bdb56dcc12a9798f
