### ISSUE TITLE
Phalcon\Mvc\Model\Resultset::serialize() returns string, no array

### ISSUE THREAD

**Issue by Chealer** [phalcon/documentation#14]
[The documentation of `Phalcon\Mvc\Model\Resultset`](https://docs.phalcon.io/4.0/fr-fr/api/phalcon_mvc#mvc-model-resultset) pretty much says that serialize() returns "a big array":

> Serializing a resultset will dump all related rows into a big array

As one may guess, this is in fact incorrect, as behavior shows it returns a string, as its synopsis indicates:

> public function serialize(): string;

It would help to make the documentation more formal.

**Comment by niden** [comment]
Resolved in 8be8c171dcb83a58b5233190c5e845212be7deac

Thank you for reporting this and apologies for the late response

**Comment by Chealer** [comment]
Thanks @niden 
[Here is the corrected page](https://docs.phalcon.io/5.5/api/phalcon_mvc/), although:

1. It was difficult to access from my Firefox 120 (which seemed to come close to crashing, surely in part due to the page's size).
2. I do not know where this page inserts itself in the documentation website.
