### ISSUE TITLE
Phalcon\Mvc\Model\Query\Builder::columns() poorly specified

### ISSUE THREAD

**Issue by Chealer** [phalcon/documentation#15]
[The documentation of the `Phalcon\Mvc\Model\Query\Builder` class's `columns()` method](https://docs.phalcon.io/4.0/fr-fr/api/phalcon_mvc#m%C3%A9thodes-34) is minimal:

> Sets the columns to be queried

As suggested by https://docs.phalcon.io/4.0/fr-fr/db-phql, more precisely:

> columns - array | string - columns to select

There are examples which hint about valid arguments. Here is another example I found:
`->columns("CQLC\Models\Notifications.*")`

**Comment by niden** [comment]
Apologies for the late reply.

This has been resolved in f893f2acaab0926b209fb58bbb44ad6c4ee62e6e

Thanks!

**Comment by Chealer** [comment]
I made a few comments about the new version on the commit, but thank you very much @niden , this is a big improvement and (mostly) addresses the specific issue which I had hit.

**Comment by niden** [comment]
@Chealer I replied to your comment also. All these have been published. Thank you for your diligence.

**Comment by Chealer** [comment]
My pleasure @niden , thanks to you 🙂
