### ISSUE TITLE
Removed "Phalcon\Model\Manager::registerNamespaceAlias()" referenced in v4 PHQL docs

### ISSUE THREAD

**Issue by hakimio** [phalcon/documentation#16]
**Describe the bug**
Removed method `Phalcon\Model\Manager::registerNamespaceAlias()` is used in [PHQL documentation](https://docs.phalcon.io/4.0/en/db-phql#:~:text=Copy-,Aliases%20in%20Namespaces,-You%20can%20define).

**Expected behavior**
Documentation should be updated.

**Comment by niden** [comment]
This has been fixed. Thank you for the report and apologies for taking this long to reply.
