### ISSUE TITLE
Class Phalcon\Config: path() method poorly specified

### ISSUE THREAD

**Issue by Chealer** [phalcon/documentation#17]
[The _Methods_ section of Phalcon\Config's documentation](https://docs.phalcon.io/4.0/en/api/phalcon_config#methods) describes path():

> `public function path( string $path, mixed $defaultValue = null, mixed $delimiter = null ): mixed | null;`
> 
> Returns a value from current config using a dot separated path.

It would greatly help to properly specify that method, indicating what value is returned.

By the way, if that is how values are obtained, renaming to something like "get" would surely clarify.

**Comment by hakimio** [comment]
It already has `get()` method inherited from [Collection](https://docs.phalcon.io/4.0/en/api/phalcon_collection) class, but they work differently. [`path()` is a wrapper on top of `get()`](https://github.com/phalcon/cphalcon/blob/v4.0.0/phalcon/Config.zep#L108).

**Comment by niden** [comment]
`path` is a nested get so to speak. 

Imagine:

```
database
    adapter: Mysql
```

```
$value = $config->get('database'); // Config object
$adapter = $value->get('adapter'); // string `Mysql`
```

vs

```
$adapter = $config->path('database.adapter');  // string `Mysql`
```

**Comment by niden** [comment]
This has been fixed in the docs. Apologies for taking this long to reply.

**Comment by Chealer** [comment]
Thank you @hakimio and @niden 
Can you mention how this was resolved @niden ?
@hakimio : in that case, I would suggest renaming to either `getByPath` or `findByPath`.

I would say this is a "symptom" of `Phalcon\Config`'s documentation being generally poor. It contains a small paragraph with an explanation of the model:

> `Phalcon\Config` is designed to simplify the access to, and the use of, configuration data within applications. It provides a nested object property based user interface for accessing this configuration data within application code.

Unfortunately, that explanation is in the `Config\Config` section, rather than directly in the namespace's. Moreover, it is unclear and far from complete:

1. The term "user interface" is confusing in this context.
2. It does not explain paths (nor delimiters).

I would suggest something like:
> `Phalcon\Config` simplifies configuration of applications.
> A `Config\Config` configuration collection represents a tree whose leaves are configuration values. Each child node of a `Config\Config` is named, and is either an external node which contains a configuration value or a subcollection which is itself a `Config\Config` instance holding nested values. Each node other than the root has a path consisting of its ancestor's name followed by a delimiter and by its own name.
> `Phalcon\Config` provides an API to access such configuration collections. Each `Config\Config` instance represents a virtual object which can be traversed in the fashion of true object properties.

I believe something like this would provide a reasonable foundation for a proper specification of `Config::path`.

It would also be important to clarify the constructor(s). Currently, they are all inherited from `Phalcon\Collection`.

**Comment by niden** [comment]
@Chealer  Have a look and let me know if this is OK please

https://docs.phalcon.io/5.5/config/

I shamelessly copied some of your text and added it there. :)

**Comment by Chealer** [comment]
Thank you @niden ; I do hope this was shameless, as your revision represents a considerable improvement. :-)

Here is what I remarked:
1. > Using path() allows for easy retrieval of the value of a nested key, however deep that might be.

    Technically, I would argue that the value of a key is the name itself. I would recommend:
    > Using path() allows for easy retrieval of a **sub-item**, however deep **it** might be.
2. > A delimited string is passed, representing each level of the object, separating nesting with the use of a delimiter (by default .).

   This is understandable but does not read very well. I suggest:
   > The mandatory argument is a string indicating the requested node's path. The string is a pathname containing the names of each of the node's ancestors and its own, starting from level 1. The root node's pathname is the empty string and a level 1 node's pathname is its own name. The pathname of a node at level 2 or more consists of its parent's pathname followed by the delimiter (by default .) followed by its name.
3. > The last parameter of path() is the delimiter to be used for splitting the passed string (path) which also denotes the nesting level.

   This can be confusing since:
   - The last parameter may depend of how many are given.
   - The end of the sentence is not clear (to me).
 
   Unless I am missing something, I would propose just:
   > The last parameter path() accepts is the delimiter which separates the names in the pathname (mandatory argument).
4. > Use the getPathDelimiter() and setPathDelimiter() methods to get or set the delimiter that the component will use. 

   This is surely not quite correct, unless these are static methods. Assuming this only sets the object's delimiter, it would be more correct to write:
   > Use the getPathDelimiter() and setPathDelimiter() methods to get and set the delimiter that the Config will use by default.
5. > The delimiter parameter in the path() method can then be used as an override for a special case, while the default delimiter is set using the getter and setter.

   The getter does not _set_ the delimiter, so I suggest:
   > The delimiter parameter in the path() method can then be used as an override for a special case, while the default delimiter is set using setPathDelimiter().

6. None of this really explains how to deal with the delimiter occurring in a node's name. If certain characters work as escape characters, they should be documented. If not, it should be documented that path() cannot be used if any of the pathname's node names contain the delimiter.

By the way:

1.  > This component can be instantiated using a PHP array directly or by reading configuration files from various formats, as described further down in the adapters section.

    I have never heard about "component instantiation" regarding software backends, and this terminology is confusing. Unless this conforms to Phalcon's jargon, I would recommend "This class can".
2. The _Get_ section contains a _Get_ sub-section, which is confusing. I suggest renaming the subsection "get" (uncapitalized).

**Comment by niden** [comment]
@Chealer 

Those have been applied. I also added a warning up there for `path()` and delimiters in keys.

**Comment by Chealer** [comment]
Thank you very much @niden , commit da43961b2f267ae0b12fbd12de7c1e5e95807a89 is nearly perfect and completes the work.
Just one remark: the `config()` function proposed at the end of the _Path_ section could come handy, but if we want the documentation to put the most important information first, I recommend to put it last (after the new warning on keys).

By the way:

1. The syntax highlighting in that page is not great. In particular, the output in [the _Merge_ section](https://docs.phalcon.io/5.5/config/#merge) is incorrectly highlighted. It is probably better to not highlight it than to use the current highlighting.
2. The intra-page table of contents is not working reliably. Sometimes, clicking has no effect. I cannot say if this is specific to this page at this time.
