### ISSUE TITLE
Installation Guide - Amazon Linux

### ISSUE THREAD

**Issue by Ultimater** [phalcon/documentation#26]
Very easy to get buried in the installation docs: https://phalcon.io/en-us/download/linux
Amazon Linux does not appear to be covered...
I had to follow: https://stackoverflow.com/questions/56623885/how-to-install-phalcon-php-on-amazon-linux
I'm thinking there should be an official "installer" repo so issues can be opened related to installation, and to smooth out the bumps in the installation process to make it much easier to follow, and less prone to issues during installation.

I'll work on trying to implement this...

**Comment by niden** [comment]
Added a section to the site about Amazon Linux

https://github.com/phalcon/phalcon.io/commit/86b361fd787b24129230a15c933f37758c5a3478

Apologies for the late reply.
