### ISSUE TITLE
\Phalcon\Db documentation issues

### ISSUE THREAD

**Issue by slothentic** [phalcon/documentation#27]
I recently upgraded to 4.0.4 and have noticed a number of errors in the documentation here: https://docs.phalcon.io/4.0/en/db-layer#create-1

Most importantly, the second parameter `schema` for all db operations is `null` in the documentation, but that causes a fatal error.

For example:

```
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Phalcon\\Db\\Adapter\\AbstractAdapter::modifyColumn() must be of the type string, null given
```

I was able to fix this by simply passing `""` an empty string as the second param.

**Comment by niden** [comment]
Apologies for taking this long to respond.

The upgrade guide should show all the changes in the interfaces but we might have missed some stuff.

The v5 is more thorough in the upgrade guide

**Comment by niden** [comment]
I am going to close this.
