### ISSUE TITLE
Custom Validator bug

### ISSUE THREAD

**Issue by wmamrak** [phalcon/documentation#28]
The messages should be appended to the validator using messageFactory method:
```
$validator->appendMessage(
  $this->messageFactory($message, $attribute)
 );
```

Location of the bug: https://docs.phalcon.io/4.0/en/validation#custom-validators

**Comment by niden** [comment]
Apologies for the late reply. This has been resolved in c2b1ff5030a9d91057d27a4778ddd1953ce522e4

Thank you
