### ISSUE TITLE
New benchmark page

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/documentation#49]
Due to the fact that current benchmarks is outdated and it was removed from the docs we need new benchmarks. I believe that the URL of benchmark page should be the same as before.

refs phalcon/docs#706

**Comment by sergeyklay** [comment]
[Web Framework Benchmarks](https://goo.gl/DOwCLt)

**Comment by niden** [comment]
For now we will not add this - the Techempower are there for those that might need that information.
