### ISSUE TITLE
"Go to repository" link (top right) points to archived repository (phalcon-orphanage/docs)

### ISSUE THREAD

**Issue by Chealer** [phalcon/documentation#51]
The top line in the header at the top of all pages on [the Phalcon Documentation website](https://docs.phalcon.io) contains a link to the documentation's source repository with a Git icon: 
![Capture d’écran 2023-12-30 à 18 42 17](https://github.com/phalcon/documentation/assets/486141/38a3f37b-068e-45ca-b943-a4ddf5ad21cb)
This link's target is https://github.com/phalcon/docs, which redirects to https://github.com/phalcon-orphanage/docs, an archived repository which does not cover Phalcon versions beyond 5.0.

This link target may be appropriate for old versions, but the repository for the documentation of current versions is this one (https://github.com/phalcon/documentation).

**Comment by niden** [comment]
This has been fixed in https://github.com/phalcon/documentation/commit/fd4aa53375ab96973f86d4ef0669a866972a5880

Thank you @Chealer
