### ISSUE TITLE
I try to fix links colors but...

### ISSUE THREAD

**Issue by borisdelev** [phalcon/documentation#58]
Hi,
I want to fix style of <a> tags, but cant find assets/stylesheets for documentation. Is there a way to do that?

It is a --md-primary-fg-color css variable and its used for header too. Maybe to set a new one only for links and make them more visible.

![image](https://github.com/phalcon/documentation/assets/4441663/828eb749-c640-4883-bf34-a7830a1523ba)

**Comment by niden** [comment]
@borisdelev you can find the css here:

https://github.com/phalcon/documentation/blob/5.6.x/docs/assets/css/extra.css

Also instructions for changing the colors (in general)

https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/


Thank you

**Comment by borisdelev** [comment]
Thinks! Hmm... as i can see... the attribute of body [data-md-color-primary] when set to _black_ -> this should fix all links & menus. After that we can place our primary color for header (for example). OR... i can replace just style for links, but not sure will fix all... 
Anyway - which one is better approach?

**Comment by niden** [comment]
We can use trial and error honestly. 

If you want to run this locally to check it out, here is what you can do:

In the repo you run this:

```sh
docker build -t phalcon-docs .
```

once it builds enter the environment:

```sh
docker run -it --rm --network host -v "$PWD":/usr/src/myapp -w /usr/src/myapp phalcon-docs /bin/bash
```

and once in that environment

```sh
mkdocs serve
```

Now you will be able to see the docs visiting `http://localhost:8000/`

The `mkdocs-material` site has quite a bit of information on how one can customize these colors. I apologize, I have no color coordination to help with this.

**Comment by borisdelev** [comment]
Hmm... i try a few times and get "repository name must be lowercase" error from docker (everything is lowercase). Will try again on other PC/Mac.

**Comment by Arhell** [comment]
i fix colors
