### ISSUE TITLE
Wrong namespace for code example DataMapper Connection

### ISSUE THREAD

**Issue by sinbadxiii** [phalcon/documentation#71]
Hi Guys,

There is a mistake in a code example on the docs page https://docs.phalcon.io/5.6/datamapper/

```php
use Phalcon\DataMapper\Connection;
```
instead
```php
use Phalcon\DataMapper\Pdo\Connection;
```

Damn it! But I can't find the place to fix it :)

**Comment by niden** [comment]
@sinbadxiii 

Here are the latest docs:

https://github.com/phalcon/documentation/edit/5.6.x/docs/datamapper.md

**Comment by niden** [comment]
Every version has a different branch. We build each version's files when a push happens in each branch with GitHub Actions.

The translations are not there - we had to remove them because it was too much complexity and not too much participation.

**Comment by niden** [comment]
Resolved here https://github.com/phalcon/documentation/pull/77 Thank you @sinbadxiii
