### ISSUE TITLE
Middleware 相关的内容不见了，是调整到其他区域了吗？

### ISSUE THREAD

**Issue by itknight** [phalcon/documentation#89]
现在我看到的中间件部分只有标题，如下：
```raw
## Middleware

### 404

### Authentication

### Tokens

### Verification

### Validation

### Response
```

这一部分是调整了吗？

**Comment by itknight** [comment]
branch version  4.1

**Comment by itknight** [comment]
after googling for a long time ,i've found that in the lateset version ,phalcon has eventManager replaced middleware , but i can hardly found any example ,is it possible to give us some example about middleware usage by eventManage , like  authentication / tokens and response , regards.

**Comment by niden** [comment]
@itknight There is no "real" middlware in Phalcon - not yet at least.

Have a look at this repository which implements that

https://github.com/phalcon/rest-api
https://github.com/phalcon/rest-api/blob/master/library/Providers/RouterProvider.php
https://github.com/phalcon/rest-api/tree/master/library/Middleware

**Comment by itknight** [comment]
> @itknight There is no "real" middlware in Phalcon - not yet at least.
> 
> Have a look at this repository which implements that
> 
> https://github.com/phalcon/rest-api https://github.com/phalcon/rest-api/blob/master/library/Providers/RouterProvider.php https://github.com/phalcon/rest-api/tree/master/library/Middleware

thanks a lot ,by these links ,i've found a better practise.
